spring:
  zipkin:
        base-url: http://localhost:9411/ 

management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            expose: '*'
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: true        